### ISSUE TITLE
`Invoke-VCFHealthReport` cmdlet fails on 4.4.1

### ISSUE THREAD

**Issue by devivmware** [vmware/powershell-module-for-vmware-cloud-foundation-reporting#138]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/powershell-module-for-cloud-foundation-reporting/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

4.4.1

### PowerShell Version

5.1

### PowerCLI Version

13.1.0

### Module Version

2.0.0

### PowerValidatedSolutions Version

2.2.0

### PowerVCF Version

2.3.0.1004

### Guest Operating System

Windows server 2019

### Environment Details

Customer Environment running on vcf 4.4.1. We were able to execute healthcheck using previous version of modules.

### Description

`Invoke-VCFHealthcheckReport` command is failing. We are able to run the API call from SDDC Manager UI without any issue. we already restarted SoS service. 

### Error or Debug Output

```powershell
{“errorCode”: “BAD_REQUEST”, “message”: “Bad request! Invalid Headers or Data. Error: {‘options’: {‘include’: {‘precheckReport’: [‘Unknown field.’]}}}“}
```

### Expected Behavior

to receive health check output

### Actual Behavior

command failing with error:

```powershell
{“errorCode”: “BAD_REQUEST”, “message”: “Bad request! Invalid Headers or Data. Error: {‘options’: {‘include’: {‘precheckReport’: [‘Unknown field.’]}}}“}
```

### Steps to Reproduce

invoking the same command.

**Comment by garlicNova** [comment]
precheckReport is an extra element in SDDC manager 4.5.0 release.  will do a version check and split the payload element when requesting for health-summary info.

**Comment by tenthirtyam** [comment]
@garlicNova You'll need to create a branch based on the v2.0.0 tag and then patch it there.

Then we could release an update v2.0.0 build with the fix.

After, I can cherry-pick it and pull into v2.1.0.

**Comment by tenthirtyam** [comment]
Patch [release v2.0.1.1000](https://www.powershellgallery.com/packages/VMware.CloudFoundation.Reporting/2.0.1.1000) has been published to the PowerShell Gallery.

```powershell
Update-Module -Name VMware.CloudFoundation.Reporting
````
