### ISSUE TITLE
Invoke-HealthReport - Invalid tar and missing argument issue

### ISSUE THREAD

**Issue by DJ-VMW** [vmware/powershell-module-for-vmware-cloud-foundation-reporting#163]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/powershell-module-for-cloud-foundation-reporting/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

4.5.1

### PowerShell Version

PowerShell Core 7.3.6

### PowerCLI Version

13.1.0.21624340

### Module Version

2.3.0.1000

### PowerValidatedSolutions Version

2.5.0.1010

### PowerVCF Version

2.3.0.1004

### Guest Operating System

Windows Server 2016

### Environment Details

Nested VCF Lab using VLC. With a Mgmt WLD, 1x VC, 1x, NSX Mgr., 1x SDDC Mgr.

### Description

After installing & loading the required Modules, defined the variable below:

```powershell
$reportpath = "C:\VCFReporting\"
$sddcManagerFqdn = "sddc-manager.vcf.sddc.lab"
$sddcManagerUser = "administrator@vsphere.local"
$sddcManagerPass = "VMware123!"
```

Ran the following command:

```powershell
invoke-VcfHealthReport -sddcManagerFqdn $sddcManagerFqdn -sddcManagerUser $sddcManagerUser -sddcManagerPass $sddcManagerpass -sddcManagerLocalUser $sddcManagerUser -sddcManagerLocalPass $sddcManagerPass -reportPath $reportPath -allDomains
```

Consistently receive the error regardless of the Local User entered. Verified all modules have been loaded. The errors don't seem to be related to anything OS, or VCF related. Strictly how the commands within the 'Invoke-VCFHealthReport' command are being interpreted.

2 folders are created within the HealthReports directory in the Report Path provided named with 5 random alphanumeric characters. Each includes the following files:

- `health-summary.tar.gz`
- `healthSummaryPayload.json`

Expanding the 'health-summary' tar file produces a nested folder structure that includes the following files:

- `health-report.log`
- `health-results.json`
- `report.json`
- `sos.log`
- `vc_appliance_services_vcenter-mgmt.vcf.sddc.lab.log`
- `vc_current_config_vcenter-mgmt.vcf.sddc.lab.log`
- `vc_services_vcenter-mgmt.vcf.sddc.lab.log`

### Error or Debug Output

https://gist.github.com/DJ-VMW/be30767e6bf9318afad1b716c636b393

### Expected Behavior

Browser should display the expected Health Report and the report should be placed in the provided report location.

### Actual Behavior

See the error provided and description.

### Steps to Reproduce

See description.

### Screenshots

![image](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-reporting/assets/95247386/ecac3a92-440b-43b3-8612-80b6087a07f8)

**Comment by tenthirtyam** [comment]
Marking this issue as closed.

**Comment by tenthirtyam** [comment]
Note: Refer to https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-reporting/pull/102.
