### ISSUE TITLE
Add support for a detailed license reporting across the VMware Cloud Foundation instance

### ISSUE THREAD

**Issue by GaryJBlake** [vmware/powershell-module-for-vmware-cloud-foundation-reporting#166]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Currently there is no easy way to get a picture of the licensing status across component of a VMware Cloud Foundation instance. The SoS Utility only gets a picture of the ESXi license status but this is only part of the story. We should expand the capability to provide covered across:

- SDDC Manager
- vCenter Server
- NSX Manager

This could be an extension of the existing report or it could be a License specific report.

### Use Case(s)

- As a VI Admin I want a quick way to check just my licenses across VMware Cloud Foundation to see if anything has expired, this should cover what SDDC Manager sees, what vCenter Server sees and what NSX Manager sees so that I can then address.

### Potential Configuration

A number of functions already exist to cover most of the use case:

- PowerValidatedSolutions has `Get-VcLicense`
- PowerVCF has `Get-VCFLicenseKey`
- Nothing exists for NSX currentlu

**Comment by tenthirtyam** [comment]
Closing based on licensing changes. [Ref](https://news.vmware.com/company/vmware-by-broadcom-business-transformation).
