### ISSUE TITLE
Add a recheck for `Invoke-VcfHealthReport` to check for `tar` if running Windows

### ISSUE THREAD

**Issue by burnsjared0415** [vmware/powershell-module-for-vmware-cloud-foundation-reporting#190]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

If for some reason you don't read the Requirements for the Module and just run the command, you will get some error messages that don't example the issue of missing the tar.exe file in c:\windows\System32. I suggest adding code to stop the run with a error message right at the beginning.

### Use Case(s)

Older Operating Systems that are not in Requirements list

### Potential Configuration

 ```powershell
Function Invoke-VcfHealthReport {
    <#
       ...

    Try {
        Clear-Host; Write-Host ""
           
           if ($PSVersionTable.PSEdition -eq "Desktop" -or $PSVersionTable.OS -like "Microsoft Windows*") {
            $tarPath = (Get-Command tar -ErrorAction SilentlyContinue).Source
            if (!($tarPath)) {
                Write-Warning "The tar utility is required to run this cmdlet. Please check the module system requirements and try again."
                return
            }
        } 

       .....
```

**Comment by tenthirtyam** [comment]
Resolved in https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-reporting/pull/191.
