### ISSUE TITLE
Add support for including the ESXi version in System Overview Report

### ISSUE THREAD

**Issue by serbiansky** [vmware/powershell-module-for-vmware-cloud-foundation-reporting#23]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [x] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [x] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

On System Overview Report we have SDDC Manager, vCenter, NSX and vRealize component version but there is no ESXi version. It will be good to have ESXi version per cluster or Hardware Overview. 

### Use Case(s)

We have situation where customer stated that they deployed whole setup with higher version then BoM. When we check System Overview Report we could not find ESXi version, and also in other pages (Health, ALert...) 
Then we notice in sddc-all-health-results.json for ESXi hosts "message": "Failed. Version mismatch found for ESXI:esxi-zg-14.hsc. BOM version 7.0.3-19482537, Component Running installed version 7.0.3-20036589 and VCF Inventory version 7.0.3-20036589 are not as expected.".

### Potential Configuration

Adding ESXi version in one of the below places of System Overview Report:

- vSphere Cluster Overview (ideally) 
- Dedicated section for ESXi only
- Hardware Overview

**Comment by tenthirtyam** [comment]
Hi @serbiansky, 👋 

How's this:

```powershell
PS > Request-EsxiOverview -server $server -user $user -pass $pass

Domain Name       : sfo-m01
Cluster Name      : sfo-m01-cl01
ESXi Host FQDN    : sfo01-m01-esx04.sfo.rainpole.io
ESXi Host Version : 7.0.3-20328353
Hardware OEM      : Dell Inc.
Hardware Platform : PowerEdge R630
CPU Sockets       : 2
CPU Cores         : 28
Memory (GB)       : 256
Status            : ASSIGNED

Domain Name       : sfo-m01
Cluster Name      : sfo-m01-cl01
ESXi Host FQDN    : sfo01-m01-esx02.sfo.rainpole.io
ESXi Host Version : 7.0.3-20328353
Hardware OEM      : Dell Inc.
Hardware Platform : PowerEdge R630
CPU Sockets       : 2
CPU Cores         : 28
Memory (GB)       : 256
Status            : ASSIGNED

Domain Name       : sfo-m01
Cluster Name      : sfo-m01-cl01
ESXi Host FQDN    : sfo01-m01-esx03.sfo.rainpole.io
ESXi Host Version : 7.0.3-20328353
Hardware OEM      : Dell Inc.
Hardware Platform : PowerEdge R630
CPU Sockets       : 2
CPU Cores         : 28
Memory (GB)       : 256
Status            : ASSIGNED

Domain Name       : sfo-m01
Cluster Name      : sfo-m01-cl01
ESXi Host FQDN    : sfo01-m01-esx01.sfo.rainpole.io
ESXi Host Version : 7.0.3-20328353
Hardware OEM      : Dell Inc.
Hardware Platform : PowerEdge R630
CPU Sockets       : 2
CPU Cores         : 28
Memory (GB)       : 256
Status            : ASSIGNED

Domain Name       : sfo-w01
Cluster Name      : sfo-w01-cl01
ESXi Host FQDN    : sfo01-w01-esx03.sfo.rainpole.io
ESXi Host Version : 7.0.3-20328353
Hardware OEM      : Dell Inc.
Hardware Platform : PowerEdge R630
CPU Sockets       : 2
CPU Cores         : 28
Memory (GB)       : 256
Status            : ASSIGNED

Domain Name       : sfo-w01
Cluster Name      : sfo-w01-cl01
ESXi Host FQDN    : sfo01-w01-esx01.sfo.rainpole.io
ESXi Host Version : 7.0.3-20328353
Hardware OEM      : Dell Inc.
Hardware Platform : PowerEdge R630
CPU Sockets       : 2
CPU Cores         : 28
Memory (GB)       : 256
Status            : ASSIGNED

Domain Name       : sfo-w01
Cluster Name      : sfo-w01-cl01
ESXi Host FQDN    : sfo01-w01-esx04.sfo.rainpole.io
ESXi Host Version : 7.0.3-20328353
Hardware OEM      : Dell Inc.
Hardware Platform : PowerEdge R630
CPU Sockets       : 2
CPU Cores         : 28
Memory (GB)       : 256
Status            : ASSIGNED
```

<img width="1763" alt="image" src="https://user-images.githubusercontent.com/7771363/205420550-3bf315f3-a0ab-47db-a8c9-92333538b824.png">

I just need to clear up the sort order.

Ryan

**Comment by tenthirtyam** [comment]
Here's another example with hosts that are unassigned and of different OEM and platform:

![image](https://user-images.githubusercontent.com/7771363/205683730-ff15fdef-032c-4153-82f1-7d2645a051b5.png)
