### ISSUE TITLE
Add support to display status of ESXi passwords in the Password section of the Health Report

### ISSUE THREAD

**Issue by lelik2be** [vmware/powershell-module-for-vmware-cloud-foundation-reporting#39]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

I think even ESXi password is set to never expires, it would be beneficial to display ESXi password in the Password section of the Health report 

### Use Case(s)

Provide the ESXi passwords with GREEN alert and a message in the in the Password section of the Health Report.

### Potential Configuration

VMware Cloud Foundation 4.4 and later.

**Comment by tenthirtyam** [comment]
This should be easily doable as this is included with the updated SoS data; however, one thing to consider is if we want to have a flag to skip inclusion of ESXi as there could be a _very long_ list of results when not using `--failuresonly`.

**Comment by tenthirtyam** [comment]
Will need to refactor `Publish-PasswordHealth` to support the inclusion of the user name and expiration. This cmdlet already pulls the ESXi host `root` and `svc-vcf-*` account password status. Then flip to use this cmdlet instead of `Publish-LocalUserExpiry`.
