### ISSUE TITLE
Add support to display "Expires In (Days)"  in the Password section of the Health Report

### ISSUE THREAD

**Issue by lelik2be** [vmware/powershell-module-for-vmware-cloud-foundation-reporting#40]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [x] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Add support to display "Expires In (Days)"  in the Password section of the Health Report.

### Use Case(s)

It would be beneficial to display "Expires In (Days)" in the Password section of the Health Report.

### Potential Configuration

VMware Cloud Foundation 4.4 or later.

**Comment by tenthirtyam** [comment]
If the known account coverage gaps from previous versions of SOS are resolved then I may be possible to enhance the output to use the JSON. 

```json
    "Password Expiry Status": {
        "sfo-vcf01.sfo.rainpole.io : vcf": {
            "area": "SDDC : sfo-vcf01.sfo.rainpole.io",
            "title": {
                "user": "vcf",
                "host": "sfo-vcf01.sfo.rainpole.io",
                "component": "SDDC",
                "cmd": "shell chage -l vcf",
                "last_change": "Sep 06, 2022",
                "expiry": "Jun 01, 2025",
                "expires_in": 908
            },
            "state": "GREEN",
            "timestamp": "Tue Dec  6 04:01:02 2022",
            "message": "SDDC password expiration date is far enough. Verified using shell chage -l vcf",
            "status": "passed",
            "alert": "GREEN"
        },
   ...
```

However, if the gaps are still present, then the existing functions may need to be modified or use a hybrid approach to combine the results with the gaps.

**Comment by tenthirtyam** [comment]
- The `Publish-PasswordHealth` cmdlets reads data from SOS Utility and adds it to the html report. Before VCF 4.4, it didnt include local user account.
- The `Publish-LocalUserExpiry` connects to individual components in SDDC and collects the data from there including local user account.
- 
As of 4.4, both cmdlets return the same data.

This enhancement will help:

- Add the password expiry to the report.
- Increases the speed of the report.

**Comment by tenthirtyam** [comment]
Will need to refactor `Publish-PasswordHealth` to support the inclusion of the user name and expiration. Then flip to use this cmdlet instead of `Publish-LocalUserExpiry`.
