### ISSUE TITLE
Add support for including comparison of installed version with BoM

### ISSUE THREAD

**Issue by serbiansky** [vmware/powershell-module-for-vmware-cloud-foundation-reporting#41]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

In System Overview Report we have deployed versions, maybe we can include comparison table to compare installed version vs BoM of current VCF version. Maybe in Health report this comparison can be useful as well. 
With this we can identify is it AP Tool used (then AP tool need to be used for upgrade) or more importantly to validate that customer didn't used manual upgrade for some components, which is not so rare case. If they customer upgraded manually to version supported by AP tool that will be easy to solve before upgrade.  But if they used versions which are not supported by AP tool then it will not be easy to solve without GSS. 

### Use Case(s)

Identifying versions of components which are not part of VCF BoM and if AP tools is not used then upgrade will not be possible for that component without GSS involvement. Not so rare customers are using direct upgrade of components like ESXi, vCenter or NSX without AP tool and with this validation we will be able to identify before upgrade. 

### Potential Configuration

Adding comparison table of currently deployed versions with VCF BoM in System Overview Report and or Health report. Color coding will be good if version is part of BoM in green and red if its not. 
If AP tool is used maybe we can add note that AP tool needs to be used for future VCF upgrades. This is documented in AP tool documentation but usually ignored by customers.

**Comment by serbiansky** [comment]
Yes, that's how last time I notice at report:
 "state": "YELLOW",
            "timestamp": "Mon Nov 21 14:30:23 2022",
            "message": "Failed. Version mismatch found for ESXI:esxi-01 BOM version 7.0.3-19482537, Component Running installed version 7.0.3-20036589 and VCF Inventory version 7.0.3-20036589 are not as expected.",
            "status": "failed",
            "alert": "YELLOW"

**Comment by tenthirtyam** [comment]
> If AP tool is used maybe we can add note that AP tool needs to be used for future VCF upgrades. This is documented in AP tool documentation but usually ignored by customers.

I think the drift for a BOM release is easily doable with some regex; however, inclusion of sync Patch Tool (_"APT"_) context might be more substantial.

One issue with bringing in APT may that we'd need to likely keep a `.json` file updated for each release and what APT supports, which could increase scope for the module and release cadence influenced by APT.

Let's discuss in the New Year.

Ryan

**Comment by tenthirtyam** [comment]
There is coverage, sans APT, in https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-reporting/pull/123.
