### ISSUE TITLE
Add support for removing HCX ESXi hosts from System Overview Report host count

### ISSUE THREAD

**Issue by serbiansky** [vmware/powershell-module-for-vmware-cloud-foundation-reporting#44]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

When HCX IX is used it create virtual ESXi hosts which is added to Datacenter directly (not part of any cluster). If customer have multiple clusters they can have multiple HCX IX ESXi hosts added to Datacenter. 

In such case when System Overview Report is generated number of hosts in Hardware Overview will be correct but in vCenter Server Overview Total Hosts will be incorrect as HCX IX hosts will be added.

### Use Case(s)

All customers with HCX IX configured as that configuration will deploy ESXi virtual appliance added to Datacenter and number of hosts in System overview Report will not be accurate.

### Potential Configuration

Goal is to identify and remove HCX IX virtual ESXi hosts from Total host count in vCenter Server Overview. One way of identifying HCX IX ESXi virtual hosts is by Server Model which is VMware Mobility Platform. 

Or other way can be by resources available on that Host which is 768 CPUs and 24 TB of RAM. 

**HCX IX Host**:

![HCX Host](https://user-images.githubusercontent.com/6720374/206752718-6a5332b5-7ea9-4b0e-8f38-42ef971cb3a3.jpg)

**Regular ESXi host** (virtual example):
![ESXi](https://user-images.githubusercontent.com/6720374/206752743-ab2623f8-51ea-4f80-af89-091f96371c66.jpg)

### References

Best explanation of HCX IX I found here, for older version, but still relevant https://www.softwaredefinedblog.com/hcx-mobility-agent-aka-dummy-host/

**Comment by tenthirtyam** [comment]
Hi @serbiansky -  could you provide an `-anonymized` of report that shows the HCX IX virtual ESXi hosts being returned in the overview report? Since the report only collects this information directly from SDDC Manager, I think that these would not appear by default.

**Comment by serbiansky** [comment]
I will request next week from some of my customers with HCX.
