### ISSUE TITLE
Add support for including the number of ESXi hosts per cluster in System Overview Report 

### ISSUE THREAD

**Issue by serbiansky** [vmware/powershell-module-for-vmware-cloud-foundation-reporting#45]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

On System Overview Report in vSphere Cluster Overview will be good to have number of servers per cluster.

### Use Case(s)

On System Overview Report we have ESXi host number details in Hardware Overview and vCenter Server Overview but if we can have number of host per cluster in vSphere Cluster Overview will be good to see the split of servers. 
In some situation we have customers with stretched cluster in MGMT where they removed one host from each AZ and that is unsupported setup which we can easily detect with this.  

### Potential Configuration

Adding number of hosts per cluster in System Overview Report/vSphere Cluster Overview.

**Comment by tenthirtyam** [comment]
Easy enough to add, Dusan!

<img width="894" alt="image" src="https://user-images.githubusercontent.com/7771363/206861978-4373921f-3a5d-48e8-ba1f-726f7821511d.png">

**Comment by serbiansky** [comment]
Wow that was fast :) thank you!
