### ISSUE TITLE
Adding module update commands in `README.md`

### ISSUE THREAD

**Issue by serbiansky** [vmware/powershell-module-for-vmware-cloud-foundation-reporting#56]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Module Version

v1.0.5.1002

### Motivation

For customers with already deployed Report Module it will be good to include Upgrade of the Module, maybe after Installation part.

### Suggestion

Adding section in Readme file Upgrading the Module after Installing the Module section, with brief description how to upgrade Reporting Module and if required other depended modules. 
```powershell
Update-Module -Name VMware.CloudFoundation.Reporting
```

**Comment by tenthirtyam** [comment]
Pull request  #57 opened to add an **Updating the Module** section for both the module and its dependencies.
