### ISSUE TITLE
`Request-NsxtEdgeUserExpiry` function does not work if NSX Edge root password is different from NSX Manager root password

### ISSUE THREAD

**Issue by joisika** [vmware/powershell-module-for-vmware-cloud-foundation-reporting#74]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/powershell-module-for-cloud-foundation-reporting/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

v4.5

### PowerShell Version

Windows Powershell 5.1

### PowerCLI Version

v13.0

### Module Version

v1.0.5

### PowerValidatedSolutions Version

v1.10

### PowerVCF Version

v2.2.0

### Guest Operating System

Windows Server 2022

### Description

Password expiry validation for NSX Edges is not working if NSX Edge root password is different from NSX Manager root password.

The issue is due to a typo in the 'Request-NsxtEdgeUserExpiry Function':

```powershell
$rootPass = (Get-VCFCredential | Where-Object { $_.credentialType -eq 'SSH' -and $_.resource.resourceName -eq $vcfNsxDetails.fqdn -and $_.resource.domainName -eq $domain }).password
```
                                            
in the `Get-VCFCredential` we are using `**$vcfNsxDetails.fqdn**` instead of `**$nsxtEdgeNode.hostname**`.

The line should become:

```powershell
$rootPass = (Get-VCFCredential | Where-Object { $_.credentialType -eq 'SSH' -and $_.resource.resourceName -eq $nsxtEdgeNode.hostname -and $_.resource.domainName -eq $domain }).password
```

### Error or Debug Output

```powershell
Invoke-VMScript : 1/11/2023 12:04:32 PM Invoke-VMScript         Failed to authenticate with the guest operating system using the supplied credentials.
At C:\Work\Reporting\VMware.CloudFoundation.Reporting.psm1:9537 char:23
+ ...   $output = Invoke-VMScript -VM ($fqdn.Split(".")[0]) -ScriptText $co ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-VMScript], InvalidGuestLogin
    + FullyQualifiedErrorId : Client20_VmGuestServiceImpl_RunScriptInGuest_ViError,VMware.VimAutomation.ViCore.Cmdlets.Commands.InvokeVmScript
```

```powershell
Request-LocalUserExpiry : You cannot call a method on a null-valued expression.
At C:\Work\Reporting\VMware.CloudFoundation.Reporting.psm1:3007 char:62
+ ... entObject = Request-LocalUserExpiry -fqdn $nsxtEdgeNode.hostname -com ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Request-LocalUserExpiry
```

### Expected Behavior

Check NSX Edge password validity.

### Actual Behavior

Exception if the root passwords are different. It the password is the same everything works.

### Steps to Reproduce

1. Deploy NSX Edges with different root password than NSX Managers
2. run the `Request-NsxtEdgeUserExpiry` function".

**Comment by tenthirtyam** [comment]
Assigning to Ivo - @joisika.
