### ISSUE TITLE
Transition to the SoS Health `/v1/system/health-summary/` APIs for bundle collection

### ISSUE THREAD

**Issue by tenthirtyam** [vmware/powershell-module-for-vmware-cloud-foundation-reporting#96]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Today, this PowerShell module uses the `Request-SoSHealthJson` cmdlet to collect the SoS Health data from SDDC Manager. This cmdlet uses the `Invoke-SddcCommand` which is essentially a call to `Invoke-VMScript` over VMware Tools and requires that the user provides the SDDC Manager `root` account password.

The purpose of this enhancement request is to transition to the SoS Health `v1/system/health-summary` API for bundle collection, whereby only the API is used. This will require that status (`/v1/system/health-summary/{id}`) of the API is checked (`IN_PROGRESS`, `COMPLETED_WITH_SUCCESS`, and else). Once completed, the payload will need to be downloaded (`/v1/system/health-summary/{id}/data`) and untarred both on Windows and Linux - which ideally should not require a third-party tool.

### Use Case(s)

- Remove the reliance on invoking the OS cmdline over VMware Tools and use the native SoS API.
- Remove the reliance on the SDDC Manager `root` password.

### Potential Configuration

TBD

### References

- [StackOverflow Thread](https://stackoverflow.com/questions/38776137/native-tar-extraction-in-powershell)

**Comment by garlicNova** [comment]
I will be working on this, please assign it to me

**Comment by tenthirtyam** [comment]
> I will be working on this, please assign it to me

Assigned to Kevin Teng (@garlicNova).
